export const GET_SHOP_DATA_FROM_DB = 'GET_SHOP_DATA_FROM_DB'


export const ShopActionsTypesAsync = {
    FETCH_COLLECTIONS_START:'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE:'FETCH_COLLECTIONS_FAILURE',
}