const actionTypes = {
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM_TO_CART:' ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART:'REMOVE_ITEM_FROM_CART',
    DECREASE_ITEM_FROM_CHECKOUT_PAGE:'DECREASE_ITEM_FROM_CHECKOUT_PAGE',
    INCREASE_ITEM_FROM_CHECKOUT_PAGE:'INCREASE_ITEM_FROM_CHECKOUT_PAGE',
    CLEAR_CART:'CLEAR_CART'
}

export default actionTypes;